kind: pipeline
name: default

steps:

- name: build
  image: node:latest
  environment:
    RELAY_KEY:
      from_secret: relay_key
    RELAY_SECRET:
      from_secret: relay_secret
    RELAY_BUCKET: ws-client-tests
  commands:
    - npm install
    - npm run build
    - make test

- name: npm-publish
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_token
    email:
      from_secret: npm_email

- name: slack
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook:
      from_secret: slack_url
    channel: general
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg